### ISSUE TITLE
Make ul not have anchor subtag

### ISSUE THREAD

**Issue by grant** [grant/grant.cm#46]
Make ul > li, not ul > a > li.

See http://stackoverflow.com/questions/12086453/wrap-anchor-tag-around-li-element

Add following css:

``` css
a {
     text-decoration: none;
     display: block;
     width: 100%;
     height: 100%;
}
```
